project:
  type: website
  output-dir: docs

format:
  revealjs:
    theme: [college-of-idaho.scss, logo.scss]
    logo: images/coilogo.png
    slide-number: true
    progress: true
    hash: true
    hash-type: number
    width: 1280
    height: 720
    transition: slide
    background-transition: fade
    navigation-mode: linear
    controls: true
    footer: "Eric Friedlander | USF Math & Data Science Colloquium 2026"
    chalkboard: false
    history: false
